s3_bucket = 'fen9li'
region = 'ap-southeast-2'
role_name = 'AWSLambdaExecutionRole'
assume_role_policy_document = 'AWSLambdaExecutionRole-Trust.json' 
attach_role_policy_arn = 'arn:aws:iam::aws:policy/AWSLambdaExecute'
